# Generated by Django 4.2 on 2023-09-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='user_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
